//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int OrderId { get; set; }
        public string ProductName { get; set; }
        public int CustomerId { get; set; }
        public int BrandID { get; set; }
        public int workOrderNo { get; set; }
        public int CriteriaID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Place { get; set; }
        public string Heading { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> Wotype { get; set; }
        public string advance { get; set; }
        public string billsubmission { get; set; }
        public string warrenty { get; set; }
        public string cancel { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Activity Activity1 { get; set; }
        public virtual Criteria Criterion { get; set; }
        public virtual SubActivity SubActivity { get; set; }
        public virtual tblBrand tblBrand { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual List<OrderDetail> OrderDetailss { get; set; }
    }
}
