//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderItemsId { get; set; }
        public int OrderID { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<int> vat { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Totals { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
