//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        public int pid { get; set; }
        public string pname { get; set; }
        public string paddress { get; set; }
        public string pphone { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
